// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOaMNTcsBdc8Clz9piBMYsFjeB848eH4',
    appId: '1:765676631577:web:a52f22f59385acc5455c88',
    messagingSenderId: '765676631577',
    projectId: 'graduation-project-2bd7b',
    authDomain: 'graduation-project-2bd7b.firebaseapp.com',
    storageBucket: 'graduation-project-2bd7b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8vh5u6uMQMu1z63eTKTY7sgOCAy6lk18',
    appId: '1:765676631577:android:92876d6e79595c4e455c88',
    messagingSenderId: '765676631577',
    projectId: 'graduation-project-2bd7b',
    storageBucket: 'graduation-project-2bd7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARNRV7ls_ed5zqSeC707h2MzOB_g17Bp0',
    appId: '1:765676631577:ios:f686c80b13303009455c88',
    messagingSenderId: '765676631577',
    projectId: 'graduation-project-2bd7b',
    storageBucket: 'graduation-project-2bd7b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication9FinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARNRV7ls_ed5zqSeC707h2MzOB_g17Bp0',
    appId: '1:765676631577:ios:f686c80b13303009455c88',
    messagingSenderId: '765676631577',
    projectId: 'graduation-project-2bd7b',
    storageBucket: 'graduation-project-2bd7b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication9FinalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyOaMNTcsBdc8Clz9piBMYsFjeB848eH4',
    appId: '1:765676631577:web:a419756b0a30d43b455c88',
    messagingSenderId: '765676631577',
    projectId: 'graduation-project-2bd7b',
    authDomain: 'graduation-project-2bd7b.firebaseapp.com',
    storageBucket: 'graduation-project-2bd7b.firebasestorage.app',
  );
}
